user = User.create(first_name: 'Anatah', last_name: 'Sam', age: 20, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'male', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 20, prefer_end_age: 20, email: 'onetwo@gmail.com', description: "You should contact me if you’re not allergic to musicians, sarcasm or witty repartee."  ,encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('http://s8.favim.com/610/150403/beautiful-beauty-black-bohemian-Favim.com-2619338.jpg'))
​
​
User.create( first_name: 'Audrey', last_name: 'Leong', age: 24, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'male', prefer_country: 'Australia', prefer_state: 'Perth', prefer_start_age: 18, prefer_end_age: 22, email: 'onetwso@gmail.com', description: "My friends describe me as easy going, passionate, creative and spontaneous" ,encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('http://static1.squarespace.com/static/53ec5e31e4b0fd0d4cf4d36f/t/551d07f7e4b0f86de55c8437/1427965947431/Crystal+Liow?format=300w'))
​
User.create( first_name: 'Sarah', last_name: 'Alexandra', age: 18, country: 'Australia', state: 'WA', gender: 'female', prefer_gender: 'male', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 18, prefer_end_age: 25, email: 'onetwweo@gmail.com', description: "A wizard in the kitchen. Gordon Ramsey once told me that I was his idol.. just kidding." ,encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('https://s-media-cache-ak0.pinimg.com/236x/ce/e2/32/cee232a9e35e09e93f05c53ce1dba489.jpg'))
​
User.create( first_name: 'Hui', last_name: 'Ying', age: 21, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'male', prefer_country: 'Australia', prefer_state: 'Melbourne', prefer_start_age: 22, prefer_end_age: 28, email: 'onewetwo@gmail.com', description: "Gym instructor looking for a stable and hopefully a long term companion", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('https://scontent.cdninstagram.com/t51.2885-15/e35/p320x320/12918010_948646085250980_2068094995_n.jpg?ig_cache_key=MTIzOTUyMTY0MTI1Mjg5OTAzNg%3D%3D.2'))
​
User.create( first_name: 'Nicole', last_name: 'Koh', age: 22, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'male', prefer_country: 'India', prefer_state: 'Dehli', prefer_start_age: 18, prefer_end_age: 20, email: 'onetwreo@gmail.com', description: "Professional, grounded and fun-loving lady looking for soulmate", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('http://2.bp.blogspot.com/-7asmlq6FcvQ/UdA1X0PIzKI/AAAAAAAAIvQ/PRbounDvYWI/s400/7034280.jpg'))
​
User.create( first_name: 'Marion', last_name: 'Tautou', age: 23, country: 'France', state: 'Venice', gender: 'female', prefer_gender: 'female', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 18, prefer_end_age: 19, email: 'onetwewo@gmail.com', description: "It has always been a dream of mine to do a road trip across Australia in an old Volkswagon.", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('https://scontent.cdninstagram.com/t51.2885-15/s320x320/e35/12976326_241052362950235_959105887_n.jpg?ig_cache_key=MTI0MDU5MDkzMDkwNDA3NjIxMw%3D%3D.2.l'))
​
User.create( first_name: 'Juliette', last_name: 'Bardot', age: 24, country: 'France', state: 'Paris', gender: 'female', prefer_gender: 'male', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 20, prefer_end_age: 21, email: 'onetwweo@gmail.com', description: "Fun, a little more fun, lots of fun!", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:("https://scontent.cdninstagram.com/t51.2885-15/s320x320/e35/13269383_1754590941421407_133356208_n.jpg?ig_cache_key=MTI1NTA2NTY3ODQwMzk0OTQxNA%3D%3D.2"))
​
​
User.create( first_name: 'Catherine', last_name: 'Eng', age: 25, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'female', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 18, prefer_end_age: 22, email: 'weonetwo@gmail.com', description: "Extra 10 bonus points if you think Backstreet Boys is the best band of all time!", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('http://static1.squarespace.com/static/53ec5e31e4b0fd0d4cf4d36f/t/551cb86ee4b06a2886eacedd/1427945598758/Lilian+Chuah?format=300w'))
​
​
User.create( first_name: 'Eva', last_name: 'Ying', age: 30, country: 'India', state: 'Bihar', gender: 'female', prefer_gender: 'male', prefer_country: 'France', prefer_state: 'Paris', prefer_start_age: 18, prefer_end_age: 23, email: 'onewetwo@gmail.com', description: "Surfers are more than welcome ;)", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('http://funnymalaysia.hornbill.netdna-cdn.com/wp-content/uploads/2015/12/chinese-girl-malaysia.jpg'))
​
User.create( first_name: 'Chloe', last_name: 'Evan', age: 20, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'female', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 18, prefer_end_age: 25, email: 'onetwowe@gmail.com', description: "Intelligent, down-to-earth and adventurous. Hit me up if you're one of them.", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('http://i.dailymail.co.uk/i/pix/2014/10/27/1414426331996_Image_galleryImage_Pic_shows_Girl_named_by_s.JPG'))
​
User.create( first_name: 'Christine', last_name: 'Ang', age: 20, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'male', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 19, prefer_end_age: 25, email: 'onettwo@gmail.com', description: "Tell me an interesting story and I'll tell you mine" ,encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('http://static1.squarespace.com/static/53ec5e31e4b0fd0d4cf4d36f/t/551d09c6e4b0a9acf9537929/1427966414704/Elaine+Ng?format=300w'))
​
User.create( first_name: 'Maybeline', last_name: 'Wen', age: 24, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'male', prefer_country: 'India', prefer_state: 'Perth', prefer_start_age: 18, prefer_end_age: 22, email: 'onetwso@gmail.com', description: "Coffee, tea or me?" ,encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('https://pbs.twimg.com/media/Bw0MS2sIgAAGW9P.jpg'))
​
User.create( first_name: 'Olivia', last_name: 'Eve', age: 18, country: 'Australia', state: 'WA', gender: 'female', prefer_gender: 'male', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 18, prefer_end_age: 25, email: 'onetwweo@gmail.com', description: "Only dog lover allowed, thanks." ,encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('http://glamradar.com/wp-content/uploads/2015/10/alpha-rama.jpg'))
​
User.create( first_name: 'Ivy', last_name: 'Yong', age: 21, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'male', prefer_country: 'Australia', prefer_state: 'Melbourne', prefer_start_age: 22, prefer_end_age: 28, email: 'onewetwo@gmail.com', description: "Love at first sight just doesn't suit me.", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('ttp://sgblogawards.omy.sg/2015/uploads/thumbs/218.jpg'))
​
User.create( first_name: 'Lucy', last_name: 'Leong', age: 22, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'male', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 18, prefer_end_age: 20, email: 'onetwreo@gmail.com', description: "Happy go luck ray of sunshine.", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('ttps://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSKrKJqj4knSRvkzPwQpYVTBhbHrDdK_lWwI2UyIjHYNfSAEjoQCg'))
​
User.create( first_name: 'Jasmine', last_name: 'Abel', age: 25, country: 'France', state: 'Venice', gender: 'female', prefer_gender: 'female', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 19, prefer_end_age: 29, email: 'onetwewo@gmail.com', description: "Searching for my true love.", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('ttps://s-media-cache-ak0.pinimg.com/236x/59/38/4d/59384dab0a8bcc61bfd1e5db7c21d5fd.jpg'))
​
User.create( first_name: 'Fanny', last_name: 'Ardant', age: 24, country: 'France', state: 'Paris', gender: 'female', prefer_gender: 'male', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 20, prefer_end_age: 21, email: 'onetwweo@gmail.com', description: "Don't waste time looking for the wrong one, save time her.", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('ttp://www.justbollywood.in/wp-content/uploads/2015/08/Khushi-Kapoor.jpg'))
​
User.create( first_name: 'Joey', last_name: 'Ling', age: 27, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'female', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 18, prefer_end_age: 29, email: 'weonetwo@gmail.com', description: "Just a Malaysian looking for love in my town.", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('ttps://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTN2xneZ6X-JBpH0f3uBbRf1R-h31XsqGpHGzLPV0mQXgyBayak'))
​
User.create( first_name: 'Akani', last_name: 'Khumbu', age: 24, country: 'South Africa', state: 'Pretoria', gender: 'female', prefer_gender: 'male', prefer_country: 'France', prefer_state: 'Paris', prefer_start_age: 18, prefer_end_age: 23, email: 'onewetwo@gmail.com', description: "Reading, eating, sleeping", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('ttps://s-media-cache-ak0.pinimg.com/736x/28/de/2e/28de2efa6d5b5735ce0b6ffb8c01f600.jpg'))
​
User.create( first_name: 'Anna', last_name: 'Ong', age: 29, country: 'Malaysia', state: 'Selangor', gender: 'female', prefer_gender: 'female', prefer_country: 'Malaysia', prefer_state: 'Selangor', prefer_start_age: 18, prefer_end_age: 25, email: 'onetwowe@gmail.com', description: "Hope I'm lucky enough to meet my future husband.", encrypted_password: SecureRandom.urlsafe_base64, remember_token: SecureRandom.urlsafe_base64, remote_image_url:('ttp://i921.photobucket.com/albums/ad55/tziaaa/IMG_2891_zpsxt6siprc.jpg'))